language: php
php:
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'
install:
  - composer install --no-interaction
# before_script: echo "extension = <extension>.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
